# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 17:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import galaxy.main.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_scoring_edits_remove_contentrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxDataCache',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('signature', models.CharField(
                    db_index=True,
                    max_length=40,
                    unique=True
                )),
                ('widget_name', models.CharField(
                    blank=True,
                    max_length=100,
                    null=True
                )),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, galaxy.main.mixins.DirtyMixin),
        ),
    ]
